spring.application.name=progetto-blog
spring.datasource.url=jdbc:mysql://localhost:3306/springBlogDatabase
spring.datasource.username=root
spring.datasource.password=140904
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true